// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIwybBBnOnK36TZQwHQAD2nDqP-jpWvHY',
    appId: '1:142899219105:web:c02998ebfacedb76c67ee0',
    messagingSenderId: '142899219105',
    projectId: 'evently-17dd4',
    authDomain: 'evently-17dd4.firebaseapp.com',
    storageBucket: 'evently-17dd4.firebasestorage.app',
    measurementId: 'G-L004D5RGP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-paEkB1RFPenfLYC0gkQOcrzVxltCP7k',
    appId: '1:142899219105:android:68982d7c144bddf5c67ee0',
    messagingSenderId: '142899219105',
    projectId: 'evently-17dd4',
    storageBucket: 'evently-17dd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8n46LAiBbY9QjkqvWPMHlPOYGJG4S2w',
    appId: '1:142899219105:ios:f7f6271f231f9336c67ee0',
    messagingSenderId: '142899219105',
    projectId: 'evently-17dd4',
    storageBucket: 'evently-17dd4.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8n46LAiBbY9QjkqvWPMHlPOYGJG4S2w',
    appId: '1:142899219105:ios:f7f6271f231f9336c67ee0',
    messagingSenderId: '142899219105',
    projectId: 'evently-17dd4',
    storageBucket: 'evently-17dd4.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIwybBBnOnK36TZQwHQAD2nDqP-jpWvHY',
    appId: '1:142899219105:web:563a4530cf9565acc67ee0',
    messagingSenderId: '142899219105',
    projectId: 'evently-17dd4',
    authDomain: 'evently-17dd4.firebaseapp.com',
    storageBucket: 'evently-17dd4.firebasestorage.app',
    measurementId: 'G-JX249YDTNQ',
  );
}
